#ifndef DEBIMETER_H
#define DEBIMETER_H

/*
 #define    RAVEN_EYEN_VSN_REG                  1009
 #define    RAVEN_EYEN_SNR_REG                  1010
 #define    RAVEN_EYEN_AGC_REG                  1012
 #define    RAVEN_EYEN_NOT_REG                  1013
 */
typedef enum dataChannelIdsApp
{
	PHOENIX_VQP = 0,
	PHOENIX_VQPF = 1,
	PHOENIX_VAVG = 2,
	PHOENIX_VRAW = 3,
	PHOENIX_VSN = 4,
	PHOENIX_SNR = 5,
	PHOENIX_AGC = 6,
	PHOENIX_NOT = 7,
	PHOENIX_TEMPERATURE = 8,
	PHOENIX_HUMIDITY = 9,
	PHOENIX_PRESSURE = 10,
	PHOENIX_STD = 11,
	PHOENIX_AMPLITUDE = 12,
	PHOENIX_LEVEL_OUTPUT = 13,
	PHOENIX_FLOW_RATE = 14,
	PHOENIX_LEVEL_INPUT = 15,
	ADS1115_MILIVOLT = 16,
	ADS1115_MILIAMPERE = 17,
	ADS1115_ADC_VALUE = 18,
	ADS1115_CALCULATED_HEIGHT_VALUE = 19,
	TOTAL_VOLUME_FLOW = 20,
	LAST_TOTAL_VOLUME_RESET = 21,
	DAILY_VOLUME_FLOW = 22
}dataChannelIdsApp;

#endif
